#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "setup-system"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

# do things here for the user that might need to happen on first setup
# maybe add brew to the bashrc?
echo '# Set PATH for Homebrew.' >> ~/.bashrc
echo '# added by snow-first-setup' >> ~/.bashrc
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc