#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "flatpak-system <flatpak id>"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 7
fi

flatpak install --system --noninteractive --or-update -y "$1"