#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "oemcomplete"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi

mkdir -p /etc/snow/
touch /etc/snow/oem-complete

# modify /etc/gdm3/daemon.conf to disable automatic login
sed -i '/^\[daemon\]/a AutomaticLoginEnable=false' /etc/gdm3/daemon.conf
sed -i '/^\[daemon\]/a AutomaticLogin=' /etc/gdm3/daemon.conf

