#!/bin/bash

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi


# check to see if there is a device that has luks2 encryption by
# checking for a device with /dev/mapper/luks-* pattern
LUKS_DEVICE=$(ls /dev/mapper/ | grep '^luks-' || true)
if [ -z "$LUKS_DEVICE" ]; then
    echo "no LUKS device found, nothing to do"
    exit 0
fi



systemd-cryptenroll --unlock-tpm2-device=auto --recovery-key > /tmp/recovery-key.txt
if [ $? -ne 0 ]; then
    echo "failed to enroll recovery key"
    exit 1
fi
cat /tmp/recovery-key.txt


